name: Hacktoberfest Auto-Label

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest label to PRs
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['hacktoberfest']
            })

      - name: Welcome new contributors
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const welcomeMessage = `
            🎃 **Welcome to Hacktoberfest 2025!** 🎃

            Thank you for your contribution to Python-Basics-to-Advanced! 

            Your pull request will be reviewed by our maintainers. Please make sure:
            - [ ] Your code follows our style guidelines
            - [ ] You've added appropriate comments and documentation
            - [ ] You've tested your changes
            - [ ] Your PR title is descriptive

            Happy coding! 🐍✨
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: welcomeMessage
            })

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Check code formatting with black
        run: black --check --diff .
